version: '3.8'

services:
  backend:
    build:
      context: ./admin 
      dockerfile: Dockerfile
    command: sh -c 'sleep 10 && python manage.py migrate && python manage.py runserver 0.0.0.0:8000'
    ports:
      - "8000:8000"
    volumes:
      - ./admin:/app 
    depends_on:
      - db
    env_file:
      - ./admin/.env 

  main:
    build:
      context: ./main
      dockerfile: Dockerfile
    command: sh -c 'sleep 10 && while ! nc -z db 3306; do sleep 3; done; python main.py'
    ports:
      - "5001:5000"
    volumes:
      - ./main:/app 
    depends_on:
      - db
      - rabbitmq
    env_file:
      - ./main/.env 

  queue:
    build:
      context: ./admin 
      dockerfile: Dockerfile
    command: sh -c 'sleep 10 && while ! nc -z rabbitmq 5672; do sleep 3; done; python -u consumer.py'
    depends_on:
      - db
      - rabbitmq

  db: 
    image: mysql:latest
    restart: always
    env_file:
      - ./.env 
    ports:
      - "33068:3306" 
    volumes:
      - db_data:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  db_data: