version: '3.8'

services:
  main:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c 'sleep 15 && python manage.py runserver 0.0.0.0:8000'
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - db
      - rabbitmq 
    env_file:
      - ./.env

  db:
    image: mysql:latest
    restart: always
    env_file:
      - ./.env
    ports:
      - "3309:3306"
    volumes:
      - db_data:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "5672:5672" 
      - "15672:15672" 
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  db_data:
