version: '3.8'

services:
  main:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c 'sleep 15 && python main.py  0.0.0.0:5000'
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - db
    env_file:
      - ./.env

  
  queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python -u consumer.py'
    depends_on:
      - db

  db:
    image: mysql:latest
    restart: always
    env_file:
      - ./.env
    ports:
      - "33068:3306"
    volumes:
      - db_data:/var/lib/mysql


volumes:
  db_data:
