version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c ' sleep 15 && python manage.py runserver 0.0.0.0:8000'
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db 

  queue:
    build:
      context: .
      dockerfile: Dockerfile 
    command: 'python consumer.py'
  
  db:  
    image: mysql:latest
    restart: always
    env_file:
      - ./.env
    ports:
      - "33066:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: